# Generated by Django 3.1.4 on 2020-12-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://icon-library.com/images/placeholder-image-icon/placeholder-image-icon-21.jpg', max_length=500),
        ),
    ]
